name: drlnd
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pytorch
  - tensorflow
  - cuda92
  - jupyter
  - notebook
  - Pillow
  - pyglet
  - PyOpenGL
  - pyvirtualdisplay
  - matplotlib
  - seaborn
  - pytest
  - docopt
  - pyyaml
  - pandas
  - scipy
  - ipykernel
  - tqdm
  - pylint
  - pip:
      - gym[atari,box2d]
      #- git+https://github.com/Kojoley/atari-py.git
      - torchvision
      - ./python
      - jupyter-http-over-ws
